# AutoPilot Ventures - Google App Engine Configuration
runtime: python311
service: autopilot-ventures

# Environment variables
env_variables:
  PYTHONUNBUFFERED: "1"
  PORT: "8080"
  GOOGLE_CLOUD_PROJECT: "autopilot-ventures"
  AUTONOMOUS_MODE: "true"
  OPERATION_DURATION_DAYS: "14"

# Instance configuration
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
  max_concurrent_requests: 50

# Resources
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Network
network:
  instance_tag: autopilot-ventures

# VPC connector for Cloud SQL
vpc_access_connector:
  name: projects/autopilot-ventures/locations/us-central1/connectors/autopilot-connector

# Entry point
entrypoint: python launch_autonomous_server.py

# Health check
readiness_check:
  app_start_timeout_sec: 300
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  initial_delay_sec: 30
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Handlers
handlers:
  - url: /.*
    script: auto
    secure: always

# Inbound services
inbound_services:
  - warmup

# Beta settings
beta_settings:
  cloud_sql_instances: autopilot-ventures:us-central1:autopilot-db 