steps:
  # Build the Docker image with production configuration
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--platform=linux/amd64'
      - '-t=gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA'
      - '-t=gcr.io/$PROJECT_ID/autopilot-ventures:latest'
      - '.'
    id: 'build-image'
  
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA']
    waitFor: ['build-image']
  
  # Push the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/autopilot-ventures:latest']
    waitFor: ['build-image']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'autopilot-ventures'
      - '--image=gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=2'
      - '--max-instances=10'
      - '--min-instances=1'
      - '--timeout=900'
      - '--concurrency=100'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-env-vars=WORKERS=2'
    id: 'deploy-cloud-run'
    waitFor: ['build-image']

images:
  - 'gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/autopilot-ventures:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 