steps:
  # Build the Docker image with minimal test configuration
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '-f', 'Dockerfile.test', '-t', 'gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA', '.']
  
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA']
  
  # Tag the image as 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/autopilot-ventures:latest']
  
  # Push the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/autopilot-ventures:latest']
  
  # Deploy to Cloud Run with extended timeout
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'autopilot-ventures'
      - '--image=gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=5'
      - '--min-instances=0'
      - '--timeout=600'
      - '--concurrency=80'
    id: 'deploy-cloud-run'

images:
  - 'gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/autopilot-ventures:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 