steps:
  # Build the Docker image with minimal resources
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '-f', 'Dockerfile.test', '-t', 'gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA', '.']
  
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA']
  
  # Deploy to Cloud Run with minimal resources
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'autopilot-ventures'
      - '--image=gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--timeout=300'
      - '--concurrency=40'
    id: 'deploy-cloud-run'

images:
  - 'gcr.io/$PROJECT_ID/autopilot-ventures:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_4' 