name: Deploy to Google Cloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  PROJECT_ID: autopilot-ventures
  REGION: us-central1
  CLUSTER_NAME: autopilot-cluster
  NAMESPACE: autopilot-ventures

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
    
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker
    
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
          --region ${{ env.REGION }} \
          --project ${{ env.PROJECT_ID }}
    
    - name: Build and push Docker image
      run: |
        docker build -f Dockerfile.gcp \
          -t gcr.io/${{ env.PROJECT_ID }}/autopilot-ventures:${{ github.sha }} \
          -t gcr.io/${{ env.PROJECT_ID }}/autopilot-ventures:latest .
        docker push gcr.io/${{ env.PROJECT_ID }}/autopilot-ventures:${{ github.sha }}
        docker push gcr.io/${{ env.PROJECT_ID }}/autopilot-ventures:latest
    
    - name: Deploy to GKE
      run: |
        kubectl set image deployment/autopilot-ventures \
          autopilot-ventures=gcr.io/${{ env.PROJECT_ID }}/autopilot-ventures:${{ github.sha }} \
          --namespace=${{ env.NAMESPACE }}
        kubectl rollout status deployment/autopilot-ventures --namespace=${{ env.NAMESPACE }}
    
    - name: Verify deployment
      run: |
        kubectl get pods --namespace=${{ env.NAMESPACE }}
        kubectl get services --namespace=${{ env.NAMESPACE }} 